spring.application.name=jobportal

spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_db
spring.datasource.username=akbar
spring.datasource.password=akbar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=change-this-secret-key-to-a-long-random-production-secret-value
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=http://localhost:5173
