spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_db
spring.datasource.username=postgres
spring.datasource.password=akbar
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=admin
spring.security.user.password=admin